# Generated by Django 4.1 on 2022-08-26 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetWallet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Carteira de ativos',
                'verbose_name_plural': 'Carteiras de ativos',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='ticker',
            options={'verbose_name': 'Ativo', 'verbose_name_plural': 'Ativos'},
        ),
        migrations.CreateModel(
            name='AssetsInWallet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('asset_wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registration.assetwallet')),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registration.ticker')),
            ],
            options={
                'verbose_name': 'Ativos na carteira',
                'verbose_name_plural': 'Ativos na carteira',
            },
        ),
    ]
