# Generated by Django 4.1 on 2022-08-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_assetwallet_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
